INSERT INTO macro (macroname, macrodescription, app, category, macrotype, macro)
VALUES (
    'Move and Hold Keys',
    'This macro automates movement by holding specific keys for a set duration.',
    'Minecraft',
    'Movement',
    'Key Press',
    '{"steps": [{"keys": "w", "hold_time": "2"}, {"keys": "e", "hold_time": "4"}, {"keys": "ed", "hold_time": "4"}], "persistent_keys": ["a"]}'
),

('Auto Mining', 
 'Automatically mines in a straight line while moving forward.', 
 'Minecreft', 
 'Automation', 
 'Key Press', 
 '{"steps": [{"keys": "LMB", "hold_time": "10"}, {"keys": "w", "hold_time": "10"}], "persistent_keys": []}'),

('Rapid Fire Clicker', 
 'Simulates rapid clicking for better reaction time.', 
 'Counter Strike 2', 
 'Combat', 
 'Clicking', 
 '{"steps": [{"keys": "LMB", "hold_time": "0.1"}, {"keys": "LMB", "hold_time": "0.1"}, {"keys": "LMB", "hold_time": "0.1"}], "persistent_keys": []}'),

('Sprint and Jump', 
 'Automatically sprints and jumps repeatedly.', 
 'Counter Strike 2', 
 'Movement', 
 'Key Press', 
 '{"steps": [{"keys": "w", "hold_time": "5"}, {"keys": "space", "hold_time": "5"}], "persistent_keys": ["ctrl"]}'),

('Auto Bridge Builder', 
 'Places blocks in front while moving.', 
 'Minecraft', 
 'Building', 
 'Key Press', 
 '{"steps": [{"keys": "S", "hold_time": "5"}, {"keys": "RMB", "hold_time": "5"}], "persistent_keys": []}'),

 ('Bunny Hop Heal', 
 'Automatically crouches and jumps while moving forward for healing during fights.', 
 'Apex Legends', 
 'Movement', 
 'Key Press', 
 '{"steps": [{"keys": "space", "hold_time": "0.1"}, {"keys": "ctrl", "hold_time": "0.1"}], "persistent_keys": ["w"]}'),

('Tap-Strafe Boost', 
 'Executes a tap-strafe movement for advanced mobility.', 
 'Apex Legends', 
 'Movement', 
 'Key Press', 
 '{"steps": [{"keys": "w", "hold_time": "0.2"}, {"keys": "space", "hold_time": "0.1"}, {"keys": "d", "hold_time": "0.1"}, {"keys": "a", "hold_time": "0.1"}], "persistent_keys": []}'),

('Rapid Fire', 
 'Allows semi-automatic weapons to fire as fast as possible.', 
 'Apex Legends', 
 'Combat', 
 'Clicking', 
 '{"steps": [{"keys": "LMB", "hold_time": "0.05"}, {"keys": "LMB", "hold_time": "0.05"}, {"keys": "LMB", "hold_time": "0.05"}], "persistent_keys": []}'),

('Quick Armor Swap', 
 'Instantly picks up the nearest armor from a death box.', 
 'Apex Legends', 
 'Looting', 
 'Key Press', 
 '{"steps": [{"keys": "E", "hold_time": "0.1"}, {"keys": "down", "hold_time": "0.1"}, {"keys": "E", "hold_time": "0.1"}], "persistent_keys": []}'),

('Super Glide', 
 'Executes a perfect super glide movement.', 
 'Apex Legends', 
 'Movement', 
 'Key Press', 
 '{"steps": [{"keys": "space", "hold_time": "0.01"}, {"keys": "shift", "hold_time": "0.01"}], "persistent_keys": []}'),

 ('Auto Sprint', 
 'Automatically sprints without holding the sprint key.', 
 'GTA 5', 
 'Movement', 
 'Key Press', 
 '{"steps": [{"keys": "shift", "hold_time": "10"}], "persistent_keys": ["w"]}'),

('Rapid Fire', 
 'Shoots semi-automatic weapons as fast as possible.', 
 'GTA 5', 
 'Combat', 
 'Clicking', 
 '{"steps": [{"keys": "LMB", "hold_time": "0.05"}, {"keys": "LMB", "hold_time": "0.05"}, {"keys": "LMB", "hold_time": "0.05"}], "persistent_keys": []}'),

('AFK Money Farm', 
 'Prevents being kicked for inactivity by performing random movements.', 
 'GTA 5', 
 'Automation', 
 'Key Press', 
 '{"steps": [{"keys": "a", "hold_time": "2"}, {"keys": "d", "hold_time": "2"}, {"keys": "s", "hold_time": "2"}, {"keys": "w", "hold_time": "2"}], "persistent_keys": []}'),

('Quick Exit Vehicle', 
 'Exits a vehicle faster by holding the exit key briefly.', 
 'GTA 5', 
 'Vehicle', 
 'Key Press', 
 '{"steps": [{"keys": "F", "hold_time": "0.2"}], "persistent_keys": []}'),

('Auto Drive', 
 'Maintains a steady speed without needing to hold the acceleration key.', 
 'GTA 5', 
 'Vehicle', 
 'Key Press', 
 '{"steps": [{"keys": "w", "hold_time": "10"}], "persistent_keys": []}'),

('Auto Save Document', 
 'Automatically saves the document every 5 minutes.', 
 'Microsoft Word', 
 'Automation', 
 'Key Press', 
 '{"steps": [{"keys": "ctrl+s", "hold_time": "0.1"}], "persistent_keys": []}'),

('Format as Heading 1', 
 'Quickly formats selected text as Heading 1.', 
 'Microsoft Word', 
 'Formatting', 
 'Key Press', 
 '{"steps": [{"keys": "ctrl+alt+1", "hold_time": "0.1"}], "persistent_keys": []}'),

('Insert Current Date & Time', 
 'Inserts the current date and time at the cursor position.', 
 'Microsoft Word', 
 'Insertion', 
 'Key Press', 
 '{"steps": [{"keys": "alt+shift+d", "hold_time": "0.1"}, {"keys": "space", "hold_time": "0.1"}, {"keys": "alt+shift+t", "hold_time": "0.1"}], "persistent_keys": []}'),

('Convert to Uppercase', 
 'Changes selected text to uppercase.', 
 'Microsoft Word', 
 'Editing', 
 'Key Press', 
 '{"steps": [{"keys": "shift+f3", "hold_time": "0.1"}], "persistent_keys": []}'),

('Find and Replace', 
 'Opens the Find and Replace dialog box.', 
 'Microsoft Word', 
 'Editing', 
 'Key Press', 
 '{"steps": [{"keys": "ctrl+h", "hold_time": "0.1"}], "persistent_keys": []}'),

 ('Paste as Plain Text', 
 'Pastes copied content without formatting.', 
 'Microsoft Word', 
 'Editing', 
 'Key Press', 
 '{"steps": [{"keys": "ctrl+shift+v", "hold_time": "0.1"}], "persistent_keys": []}'),

('Select All', 
 'Selects the entire document.', 
 'Microsoft Word', 
 'Editing', 
 'Key Press', 
 '{"steps": [{"keys": "ctrl+a", "hold_time": "0.1"}], "persistent_keys": []}'),

('Duplicate Line', 
 'Copies and pastes the current line below.', 
 'Microsoft Word', 
 'Editing', 
 'Key Press', 
 '{"steps": [{"keys": "shift+home", "hold_time": "0.1"}, {"keys": "ctrl+c", "hold_time": "0.1"}, {"keys": "end", "hold_time": "0.1"}, {"keys": "enter", "hold_time": "0.1"}, {"keys": "ctrl+v", "hold_time": "0.1"}], "persistent_keys": []}'),

('Bold, Italic, Underline', 
 'Toggles bold, italic, and underline on selected text.', 
 'Microsoft Word', 
 'Formatting', 
 'Key Press', 
 '{"steps": [{"keys": "ctrl+b", "hold_time": "0.1"}, {"keys": "ctrl+i", "hold_time": "0.1"}, {"keys": "ctrl+u", "hold_time": "0.1"}], "persistent_keys": []}'),

('Insert Page Break', 
 'Inserts a new page at the cursor position.', 
 'Microsoft Word', 
 'Insertion', 
 'Key Press', 
 '{"steps": [{"keys": "ctrl+enter", "hold_time": "0.1"}], "persistent_keys": []}'),

('Insert Quick Table', 
 'Opens the table insert menu for quick selection.', 
 'Microsoft Word', 
 'Insertion', 
 'Key Press', 
 '{"steps": [{"keys": "alt+n", "hold_time": "0.1"}, {"keys": "t", "hold_time": "0.1"}], "persistent_keys": []}'),

('Zoom In', 
 'Increases the zoom level in the document.', 
 'Microsoft Word', 
 'View', 
 'Key Press', 
 '{"steps": [{"keys": "ctrl+plus", "hold_time": "0.1"}], "persistent_keys": []}'),

('Zoom Out', 
 'Decreases the zoom level in the document.', 
 'Microsoft Word', 
 'View', 
 'Key Press', 
 '{"steps": [{"keys": "ctrl+minus", "hold_time": "0.1"}], "persistent_keys": []}'),

('Center Align Text', 
 'Centers the selected text.', 
 'Microsoft Word', 
 'Formatting', 
 'Key Press', 
 '{"steps": [{"keys": "ctrl+e", "hold_time": "0.1"}], "persistent_keys": []}'),

('Bullet List', 
 'Creates a bulleted list at the cursor position.', 
 'Microsoft Word', 
 'Formatting', 
 'Key Press', 
 '{"steps": [{"keys": "ctrl+shift+l", "hold_time": "0.1"}], "persistent_keys": []}'),

 ('Auto Mining Loop', 
 'Continuously mines blocks in front of the player.', 
 'Terraria', 
 'Automation', 
 'Looping', 
 '{"steps": [{"keys": "LMB", "hold_time": "0.5"}], "persistent_keys": ["LMB"]}'),

('Auto Attack Loop', 
 'Continuously swings melee weapon or fires ranged weapon.', 
 'Terraria', 
 'Combat', 
 'Looping', 
 '{"steps": [{"keys": "LMB", "hold_time": "0.2"}], "persistent_keys": ["LMB"]}'),

('Auto Bridge Builder', 
 'Places blocks in front while moving forward.', 
 'Terraria', 
 'Building', 
 'Looping', 
 '{"steps": [{"keys": "w", "hold_time": "0.1"}, {"keys": "RMB", "hold_time": "0.1"}], "persistent_keys": ["d"]}'),

('Auto Fishing', 
 'Automatically casts the fishing rod and reels it in.', 
 'Terraria', 
 'Fishing', 
 'Looping', 
 '{"steps": [{"keys": "RMB", "hold_time": "1"}, {"keys": "RMB", "hold_time": "1"}], "persistent_keys": []}'),

('AFK Enemy Farm', 
 'Repeatedly swings a melee weapon to kill enemies while AFK.', 
 'Terraria', 
 'Combat', 
 'Looping', 
 '{"steps": [{"keys": "LMB", "hold_time": "0.3"}], "persistent_keys": []}'),

 ('Auto Mining Loop', 
 'Continuously mines blocks in front of the player.', 
 'Minecraft', 
 'Automation', 
 'Looping', 
 '{"steps": [{"keys": "LMB", "hold_time": "0.5"}], "persistent_keys": ["LMB"]}'),

('Auto Attack Loop', 
 'Continuously swings a melee weapon to attack mobs.', 
 'Minecraft', 
 'Combat', 
 'Looping', 
 '{"steps": [{"keys": "LMB", "hold_time": "0.3"}], "persistent_keys": ["LMB"]}'),

('Auto Fishing', 
 'Automatically casts the fishing rod and reels it in.', 
 'Minecraft', 
 'Fishing', 
 'Looping', 
 '{"steps": [{"keys": "RMB", "hold_time": "1"}, {"keys": "RMB", "hold_time": "2"}], "persistent_keys": []}'),

('Auto Walk', 
 'Makes the player walk forward indefinitely.', 
 'Minecraft', 
 'Movement', 
 'Looping', 
 '{"steps": [{"keys": "w", "hold_time": "0.1"}], "persistent_keys": ["w"]}'),

('AFK XP Farm', 
 'Repeatedly swings a weapon for AFK farming XP.', 
 'Minecraft', 
 'Combat', 
 'Looping', 
 '{"steps": [{"keys": "LMB", "hold_time": "0.2"}], "persistent_keys": []}'),

('Auto Parkour Jump', 
 'Automatically jumps while moving forward.', 
 'Minecraft', 
 'Movement', 
 'Looping', 
 '{"steps": [{"keys": "space", "hold_time": "0.1"}], "persistent_keys": ["w"]}'),

('Auto Build', 
 'Automatically places blocks in front while moving.', 
 'Minecraft', 
 'Building', 
 'Looping', 
 '{"steps": [{"keys": "RMB", "hold_time": "0.1"}], "persistent_keys": ["w"]}'),

('Auto Clicker', 
 'Repeatedly clicks for fast interactions.', 
 'Minecraft', 
 'Combat', 
 'Looping', 
 '{"steps": [{"keys": "LMB", "hold_time": "0.05"}], "persistent_keys": []}'),

('Auto Bridge', 
 'Places blocks while crouching and walking backwards.', 
 'Minecraft', 
 'Building', 
 'Looping', 
 '{"steps": [{"keys": "s", "hold_time": "0.1"}, {"keys": "shift", "hold_time": "0.1"}, {"keys": "RMB", "hold_time": "0.2"}], "persistent_keys": ["s", "shift"]}'),

('Auto Sprint', 
 'Automatically sprints without holding the key.', 
 'Minecraft', 
 'Movement', 
 'Looping', 
 '{"steps": [{"keys": "w", "hold_time": "0.1"}, {"keys": "ctrl", "hold_time": "0.1"}], "persistent_keys": ["w"]}');